name: php-workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      
      - name: Build Docker Image
        run: docker build -t melvinsamuel070/php:0.0.1 .
      
      
      - name: Push Docker Image
        run: docker push melvinsamuel070/php:0.0.1
      
      - name: PHP testing actions
        uses: 104corp/docker-php-testing@master

      - name: Deploy Image to EC2 Instance
        env:
          KEY_FILE: ${{ secrets.EC2_KEY }}
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "${KEY_FILE}" > private-key.pem
          chmod 600 private-key.pem
          ssh -o StrictHostKeyChecking=no -i private-key.pem ${EC2_USER}@${EC2_HOST} \
          private-key.pem

      - name: Install Docker on EC2
        uses: melvinsamuel070/install-docker-actions@v1
      - name: making docker a sudoer
        run: sudo usermod -aG docker $USER

      - name: clone the repository
        run: |
           git clone github.com/melvinsamuel070/base_blog.git
           cd bse_blog
           docker compose up -d
           docker compose ps
           docker compose logs
           docker compose down

      - name: Send Email Notification for Deployment Success
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deployment Success: CD Pipeline"
          body: "The deployment of your application completed successfully."
          to: kingsamuel412@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}     


      
      

          

          
              