name: php-workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build Docker Image
        run: docker build -t melvinsamuel070/php:1.1.0 .

      - name: Docker Hub Push
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}"
      
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push to Docker Hub
        run: docker push melvinsamuel070/php:1.1.0
  
      - name: PHP Testing
        uses: 104corp/docker-php-testing@master

        
  
      - name: Deploy Image to EC2 Instance
        run: |
            echo "${{ secrets.EC2_KEY }}" > private-key.pem
            chmod 600 private-key.pem
            ssh -o StrictHostKeyChecking=no -i private-key.pem ubuntu@${{ secrets.INSTANCE_IP }} 
            sudo apt-get update

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
            
      - name: Clone Repository and Start Docker Compose
        run: |
          git clone https://github.com/melvinsamuel070/base_blog.git base_blog
          cd base_blog
          docker compose up --build -d
          docker compose ps
          docker compose logs

      - name: Send Email Notification for Deployment Success
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deployment Success: CD Pipeline"
          body: |
          to: kingsamuel412@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}