name: php-workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   DOCKER_TAG: ${{ github.sha }}  # Use commit SHA as the tag

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          # echo "Building Docker image with tag:
          docker build -t melvinsamuel070/php:0.0.1 .

      - name: Login to DockerHub
        run: |
          echo "Logging in to DockerHub"
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          echo "Pushing Docker image to DockerHub"
          docker push melvinsamuel070/php:0.0.1-$DOCKER_TAG || exit 1

      - name: PHP Testing
        uses: 104corp/docker-php-testing@master

      - name: Deploy Image to EC2 Instance
        env:
          KEY_FILE: ${{ secrets.EC2_KEY }}
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "${KEY_FILE}" > private-key.pem
          chmod 600 private-key.pem
          ssh -o StrictHostKeyChecking=no -i private-key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          EOF

      - name: Clone Repository and Start Docker Compose
        run: |
          git clone https://github.com/melvinsamuel070/base_blog.git
          cd base_blog
          docker-compose up -d
          docker-compose ps
          docker-compose logs
          EOF

      - name: Send Email Notification for Deployment Success
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deployment Success: CD Pipeline"
          body: |
            The deployment of your application completed successfully.
            Branch: ${{ github.ref }}
            Commit SHA: ${{ github.sha }}
          to: kingsamuel412@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}